### PR TITLE
be Scala 2.13 friendly

### PR DESCRIPTION
**Pull request by SethTisue**
for the Scala 2.13 community build. (yes, there already is one!)

### CODE REVIEW

**Comment by SethTisue** [comment]
hi, anybody out there who can review/merge this...?

**Comment by ghost** [comment]
Hi @SethTisue,

Very sorry for the delay on this, I've been snowed under at $WORK recently. I'll do my very best to look at this this evening (ie in a few hours from now :smile: )

**Comment by SethTisue** [comment]
@BennyHill on the one hand, there's no rush, but on the other hand, I'm still interested in getting this in.

**Comment by ghost** [comment]
Oh man.....

I'm doing this NOW!

**Comment by ghost** [comment]
LGTM - I've also downloaded the PR locally just to make sure

**Comment by ghost** [comment]
As this is a small build change, and I've let this be open open for too long, I'll just merge this, now

**Comment by SethTisue** [comment]
thank you :-)

**Pull request merged**
